name: Publicar README no GitHub Pages

on:
  push:
    branches:
      - main # ou master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Converter Markdown para HTML
        uses: geosaber/geostat@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # O arquivo README.md será convertido em index.html
      - name: Deploy
        uses: actions/deploy-pages@v4
